FROM mcr.microsoft.com/devcontainers/base:jammy

ARG DEBIAN_FRONTEND=noninteractive
ARG USER=vscode

RUN DEBIAN_FRONTEND=noninteractive \
    && apt-get update \ 
    && apt-get install -y build-essential --no-install-recommends make \
        ca-certificates \
        git \
        libssl-dev \
        zlib1g-dev \
        libbz2-dev \
        libreadline-dev \
        libsqlite3-dev \
        wget \
        curl \
        llvm \
        libncurses5-dev \
        xz-utils \
        tk-dev \
        libxml2-dev \
        libxmlsec1-dev \
        libffi-dev \
        liblzma-dev \
        sudo

RUN usermod -aG sudo $USER

USER $USER
ARG HOME="/home/$USER"
ARG PYTHON_VERSION=3.10

ENV PYENV_ROOT="${HOME}/.pyenv"
ENV PATH="${HOME}/.moon/bin:${PYENV_ROOT}/shims:${PYENV_ROOT}/bin:${HOME}/.local/bin:$PATH"

RUN echo "done 1" \
    && curl https://pyenv.run | bash \
    && echo "done 2" \
    && pyenv install ${PYTHON_VERSION} \
    && echo "done 3" \
    && pyenv global ${PYTHON_VERSION} \
    && echo "done 4" \
    && curl -sSL https://install.python-poetry.org | python3 - \
    && poetry config virtualenvs.in-project true \
    && echo "done 5" \
    && curl -fsSL https://moonrepo.dev/install/moon.sh | bash \
    && echo "done 6"

USER root
RUN curl -sL https://deb.nodesource.com/setup_18.x | bash - \
    && apt-get install -y nodejs \
    && echo "done 7"

WORKDIR /home/$USER/app
COPY . .

RUN chown -R $USER:$USER /home/$USER/app

USER $USER
WORKDIR /home/$USER/app/frontend
RUN npm install \
    && echo "done 8"

RUN sudo npm install -g create-react-app next \
    && echo "done 9"

USER $USER

ENV PATH="${HOME}/.npm-global/bin:$PATH"
RUN npm config set prefix '${HOME}/.npm-global'
